version: "3"

services:
  test-alpine:
    container_name: test-alpine
    restart: always
    image: nginx:alpine
    ports:
      - '8081:80'
    volumes:
      - ./:/var/www
      - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  test-app:
    container_name: test-app
    restart: always
    build: ./docker/local/php-fpm
    working_dir: /var/www
    ports:
      - '9001:9000'
      - '8091:8090'
    volumes:
      - ./:/var/www
      - ./docker/local/php-fpm/php-ini.ini:/usr/local/etc/php/conf.d/90-custom.ini

  test-db:
    image: library/mysql:5.7.8
    restart: always
    container_name: test-db
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"

volumes:
  test-db:
    driver: local
