version: "3"

services:
    nginx-alpine:
        container_name: nginx-alpine
        restart: always
        image: nginx:alpine
        ports:
            - '8081:80'
        volumes:
            - ../../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#todo check

    php-app:
        container_name: php-app
        restart: always
        build: ./php-fpm
        working_dir: /var/www
        ports:
            - '9001:9000'
            - '8091:8090'
        volumes:
            - ../../:/var/www
            - ./php-fpm/php-ini.ini:/usr/local/etc/php/conf.d/90-custom.ini
#todo check
    db:
      image: library/mysql:5.7.8
      restart: always
      container_name: db
      env_file:
        - "../../.env"
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "3306:3306"

volumes:
  mysqldb:
    driver: local
